export const CLIENT_CONNECT = 'CLIENT_CONNECT';
export const CLIENT_ERR = 'CLIENT_ERR';
export const CLIENT_CONNECT_FAILURE = 'CLIENT_CONNECT_FAILURE';
export const CLIENT_DISCONNECT = 'CLIENT_DISCONNECT';


export const STATS_UPDATE_DEVICES = 'STATS_UPDATE_DEVICES';
export const STATS_UPDATE_DEVICEIDS = 'STATS_UPDATE_DEVICEIDS';
export const STATS_UPDATE_CHANNELS = 'STATS_UPDATE_CHANNELS';
export const STATS_UPDATE_CHANNEL_NAMES = 'STATS_UPDATE_CHANNEL_NAMES';

export const DEVICES_API_UPDATE = 'DEVICES_API_UPDATE';
export const DEVICE_UPDATE = "DEVICE_UPDATE";

export const ROBOT_UPDATE = "ROBOT_UPDATE";
export const ROBOT_UNSUBSCRIBE = "ROBOT_UNSUBSCRIBE";



export const CHANNEL_SUBSCRIBE = 'CHANNEL_SUBSCRIBE';
export const CHANNEL_UNSUBSCRIBE = 'CHANNEL_UNSUBSCRIBE';
export const CHANNEL_UPDATE = 'CHANNEL_UPDATE';
export const CHANNEL_MESSAGE = 'CHANNEL_MESSAGE';
